<?php

use Illuminate\Database\Seeder;
use App\Nacionalidad;

class NacionalidaTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        Nacionalidad::create([
            'id_nacionalidad'=>4,
            'nacionalidad'=>'AFGANISTAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>8,
            'nacionalidad'=>'ALBANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>12,
            'nacionalidad'=>'ARGELIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>16,
            'nacionalidad'=>'SAMOA AMERICANA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>20,
            'nacionalidad'=>'ANDORRA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>24,
            'nacionalidad'=>'ANGOLA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>28,
            'nacionalidad'=>'ANTIGUA AND BARBUDA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>31,
            'nacionalidad'=>'AZERBAIYAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>32,
            'nacionalidad'=>'ARGENTINA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>36,
            'nacionalidad'=>'AUSTRALIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>40,
            'nacionalidad'=>'AUSTRIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>44,
            'nacionalidad'=>'LAS BAHAMAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>48,
            'nacionalidad'=>'BAREIN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>50,
            'nacionalidad'=>'BANGLADES',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>51,
            'nacionalidad'=>'ARMENIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>52,
            'nacionalidad'=>'BARBADOS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>56,
            'nacionalidad'=>'BELGICA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>60,
            'nacionalidad'=>'BERMUDAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>64,
            'nacionalidad'=>'BUTAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>68,
            'nacionalidad'=>'BOLIVIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>70,
            'nacionalidad'=>'BOSNIA Y HERZEGOVINA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>72,
            'nacionalidad'=>'BOTSUANA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>74,
            'nacionalidad'=>'ISLA BOUVET',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>76,
            'nacionalidad'=>'BRASIL',
            'condicion'=>true
          ]);
    
          Nacionalidad::create([
            'id_nacionalidad'=>84,
            'nacionalidad'=>'BELICE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>86,
            'nacionalidad'=>'TERRITORIO BRITANICO DEL OCEANO INDICO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>90,
            'nacionalidad'=>'ISLA SALOMON',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>92,
            'nacionalidad'=>'ISLAS VIRGENES BRITANICAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>96,
            'nacionalidad'=>'BRUNEL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>100,
            'nacionalidad'=>'BULGARIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>104,
            'nacionalidad'=>'BIRMANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>108,
            'nacionalidad'=>'BURUNDI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>112,
            'nacionalidad'=>'BIELORRUSIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>116,
            'nacionalidad'=>'CAMBOYA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>120,
            'nacionalidad'=>'CAMERUN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>124,
            'nacionalidad'=>'CANADA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>132,
            'nacionalidad'=>'CABO VERDE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>136,
            'nacionalidad'=>'ISLAS CAIMAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>140,
            'nacionalidad'=>'REPUBLICA CENTROAFRICANA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>144,
            'nacionalidad'=>'SRI LANKA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>148,
            'nacionalidad'=>'CHAD',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>152,
            'nacionalidad'=>'CHILE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>156,
            'nacionalidad'=>'CHINA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>158,
            'nacionalidad'=>'TAIWAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>162,
            'nacionalidad'=>'ISLA DE NAVIDAD',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>166,
            'nacionalidad'=>'ISLA COCOS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>170,
            'nacionalidad'=>'COLOMBIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>174,
            'nacionalidad'=>'COMORAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>175,
            'nacionalidad'=>'MAYOTTE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>178,
            'nacionalidad'=>'REPUBLICA DEL CONGO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>180,
            'nacionalidad'=>'REPUBLICA DEMOCRATICA DEL CONGO ',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>184,
            'nacionalidad'=>'ISLAS COOK',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>188,
            'nacionalidad'=>'COSTA RICA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>191,
            'nacionalidad'=>'CROACIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>192,
            'nacionalidad'=>'CUBA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>196,
            'nacionalidad'=>'CHIPRE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>203,
            'nacionalidad'=>'REPUBLICA CHECA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>208,
            'nacionalidad'=>'DINAMARCA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>212,
            'nacionalidad'=>'DOMINICA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>214,
            'nacionalidad'=>'REPUBLICA DOMINICANA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>218,
            'nacionalidad'=>'ECUADOR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>222,
            'nacionalidad'=>'EL SALVADOR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>226,
            'nacionalidad'=>'GUINEA ECUATORIAL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>231,
            'nacionalidad'=>'ETIOPIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>232,
            'nacionalidad'=>'ERITREA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>233,
            'nacionalidad'=>'ESTONIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>234,
            'nacionalidad'=>'ISLAS FEROE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>238,
            'nacionalidad'=>'ISLAS MALVINAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>239,
            'nacionalidad'=>'OSLAS GEORGIAS DEL SUR Y SANDWICH DEL SUR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>242,
            'nacionalidad'=>'FIYI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>246,
            'nacionalidad'=>'FINLADIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>248,
            'nacionalidad'=>'ALAND',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>250,
            'nacionalidad'=>'FRANCIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>254,
            'nacionalidad'=>'GUAYANA FRANCESA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>258,
            'nacionalidad'=>'POLINESIA FRANCESA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>260,
            'nacionalidad'=>'TERRITORIOS AUSTRALES FRANCESES',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>262,
            'nacionalidad'=>'YIBUTI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>266,
            'nacionalidad'=>'GABON ',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>268,
            'nacionalidad'=>'GEORGIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>270,
            'nacionalidad'=>'GAMBIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>275,
            'nacionalidad'=>'condicion DE PALESTINA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>276,
            'nacionalidad'=>'ALEMANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>288,
            'nacionalidad'=>'GHANA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>292,
            'nacionalidad'=>'GIBRALTAR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>296,
            'nacionalidad'=>'KIRIBATI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>300,
            'nacionalidad'=>'GRECIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>304,
            'nacionalidad'=>'GROENLANDIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>308,
            'nacionalidad'=>'GRANADA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>312,
            'nacionalidad'=>'GUADALUPE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>316,
            'nacionalidad'=>'GUAM',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>320,
            'nacionalidad'=>'GUATEMALA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>324,
            'nacionalidad'=>'GUINEA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>328,
            'nacionalidad'=>'GUYANA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>332,
            'nacionalidad'=>'HAITI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>334,
            'nacionalidad'=>'AUSTRALIA ISLAS HEARD Y MCDONALD',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>336,
            'nacionalidad'=>'CIUDAD DEL VATICANO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>340,
            'nacionalidad'=>'HONDURAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>344,
            'nacionalidad'=>'HONG KONG',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>348,
            'nacionalidad'=>'HUNGRIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>352,
            'nacionalidad'=>'ISLANDIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>356,
            'nacionalidad'=>'INDIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>360,
            'nacionalidad'=>'INDONESIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>364,
            'nacionalidad'=>'IRAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>372,
            'nacionalidad'=>'IRLANDA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>376,
            'nacionalidad'=>'ISRAEL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>380,
            'nacionalidad'=>'ITALIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>384,
            'nacionalidad'=>'COSTA DE MARFIL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>388,
            'nacionalidad'=>'JAMAICA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>392,
            'nacionalidad'=>'JAPON',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>398,
            'nacionalidad'=>'KAZAJISTAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>400,
            'nacionalidad'=>'JORDANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>404,
            'nacionalidad'=>'KENIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>408,
            'nacionalidad'=>'COREA DEL NORTE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>410,
            'nacionalidad'=>'COREA DEL SUR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>414,
            'nacionalidad'=>'KUWAIT',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>417,
            'nacionalidad'=>'KIRGUISTAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>418,
            'nacionalidad'=>'LAOS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>422,
            'nacionalidad'=>'LIBANO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>426,
            'nacionalidad'=>'LESOTO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>428,
            'nacionalidad'=>'LETONIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>430,
            'nacionalidad'=>'LIBERIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>434,
            'nacionalidad'=>'LIBIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>438,
            'nacionalidad'=>'LIECHTENSTEIN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>440,
            'nacionalidad'=>'LITUANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>442,
            'nacionalidad'=>'LUXEMBURGO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>446,
            'nacionalidad'=>'MACAO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>450,
            'nacionalidad'=>'MADAGASCAR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>454,
            'nacionalidad'=>'MALAUI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>458,
            'nacionalidad'=>'MALASIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>462,
            'nacionalidad'=>'MALDIVAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>466,
            'nacionalidad'=>'MALI',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>470,
            'nacionalidad'=>'MALTA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>474,
            'nacionalidad'=>'MARTINICA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>478,
            'nacionalidad'=>'MAURITANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>480,
            'nacionalidad'=>'MAURICIO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>484,
            'nacionalidad'=>'MEXICO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>492,
            'nacionalidad'=>'MONACO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>496,
            'nacionalidad'=>'MONGOLIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>498,
            'nacionalidad'=>'MOLDAVIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>499,
            'nacionalidad'=>'MONTENEGRO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>500,
            'nacionalidad'=>'MONTSERRAT',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>504,
            'nacionalidad'=>'MARRUECOS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>508,
            'nacionalidad'=>'MOZAMBIQUE ',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>512,
            'nacionalidad'=>'OMAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>516,
            'nacionalidad'=>'NAMIBIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>520,
            'nacionalidad'=>'NAURU',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>524,
            'nacionalidad'=>'NEPAL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>528,
            'nacionalidad'=>'PAISES BAJOS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>530,
            'nacionalidad'=>'ANTILLAS NEERLANDESAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>531,
            'nacionalidad'=>'CURAZAO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>533,
            'nacionalidad'=>'ARUBA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>540,
            'nacionalidad'=>'NUEVA CALEDONIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>548,
            'nacionalidad'=>'VANUATU',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>554,
            'nacionalidad'=>'NUEVA ZELANDA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>558,
            'nacionalidad'=>'NICARAGUA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>566,
            'nacionalidad'=>'NIGERIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>570,
            'nacionalidad'=>'NIUE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>574,
            'nacionalidad'=>'NORFOLK',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>578,
            'nacionalidad'=>'NORUEGA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>580,
            'nacionalidad'=>'ISLAS MARIANAS DEL NORTE',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>583,
            'nacionalidad'=>'MICRONESIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>584,
            'nacionalidad'=>'ISLAS MARSHALL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>585,
            'nacionalidad'=>'PALAOS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>586,
            'nacionalidad'=>'OAKISTAN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>591,
            'nacionalidad'=>'PANAMA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>598,
            'nacionalidad'=>'PAPUA NUEVA GUINEA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>600,
            'nacionalidad'=>'PARAGUAY',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>604,
            'nacionalidad'=>'PERU',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>608,
            'nacionalidad'=>'FILIPINAS',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>612,
            'nacionalidad'=>'ISLAS PITCAIRN',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>616,
            'nacionalidad'=>'POLONIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>620,
            'nacionalidad'=>'PORTUGAL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>624,
            'nacionalidad'=>'GUINEA-BISAU',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>626,
            'nacionalidad'=>'TIMOR ORIENTAL',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>630,
            'nacionalidad'=>'PUERTO RICO',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>634,
            'nacionalidad'=>'CATAR',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>638,
            'nacionalidad'=>'REUNION',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>642,
            'nacionalidad'=>'RUMANIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>643,
            'nacionalidad'=>'RUSIA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>646,
            'nacionalidad'=>'RUANDA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>652,
            'nacionalidad'=>'SAN BARTOLOME',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>654,
            'nacionalidad'=>'SAN BARTOLOME',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>659,
            'nacionalidad'=>'SAN CRISTOBAL Y NIEVES',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>660,
            'nacionalidad'=>'ANGUILA',
            'condicion'=>true
          ]);
          Nacionalidad::create([
            'id_nacionalidad'=>662,
            'nacionalidad'=>'LUXEMBURGO',
            'condicion'=>true
          ]);
    }
}
